#!/bin/bash

#/home/root/fac/led_blink &

led_blink(){
	while [ "1" == "1" ];
	do

        echo 50 > /sys/class/backlight/lumi_r/brightness
        sleep 0.1
        echo 0 > /sys/class/backlight/lumi_r/brightness
        sleep 0.1

	done
}

led_blink &

ifconfig $1 down
ifconfig $1 up

pkill -9  wpa_supplicant

wpa_supplicant -B -Dnl80211 -i $1 -c/home/root/fac/wpa_supplicant.conf

udhcpc -i $1

killall link_wifi

echo 0 > /sys/class/backlight/lumi_r/brightness
