#!/bin/bash

#/home/root/set_zibee_pin.sh 
#40 MISO, 41 Reset
if [ ! -f "/tmp/set_ota_io" ]; then
	memtool 20E00E4=15 > /tmp/NULL
	memtool 20E00E8=15 > /tmp/NULL
	
	echo 40 > /sys/class/gpio/export
	echo 41 > /sys/class/gpio/export

	touch /tmp/set_ota_io
fi
	echo out > /sys/class/gpio/gpio40/direction 
	echo out > /sys/class/gpio/gpio41/direction 

	echo 1 > /sys/class/gpio/gpio40/value 
	echo 1 > /sys/class/gpio/gpio41/value 
	

if [ $# == 0 ]; then
	a=`/home/root/iot_jp -s /dev/ttymxc1 -t 2> /tmp/null | grep "MAC" -A 1`
	if [ ! -n "$a" ];then
		echo "Fail"
	else
		echo $a
	fi
fi

if [ $# == 1 ];then
	/home/root/iot_jp -s /dev/ttymxc1 -f $1
fi

echo 0 > /sys/class/gpio/gpio40/value
echo in > /sys/class/gpio/gpio40/direction

echo 0 > /sys/class/gpio/gpio41/value
sleep 0.1
echo 1 > /sys/class/gpio/gpio41/value
