#ifndef __ZIGBEE_ENUM_H__
#define __ZIGBEE_ENUM_H__

#include <string>

#if 0
typedef enum device_model
{
	LUMI_GATEWAY = 0,
	LUMI_SENSOR_SWITCH = 1,
	LUMI_SENSOR_MOTION = 2,
	LUMI_SENSOR_MAGNET = 3,
	LUMI_ZIGBEE_COMMON_CONTROLLER = 4,
	LUTUO_ENOCEAN_CONTROLLER = 5,

	YEE_LIGHT_RGB = 6,

	LUMI_CTRL_NEUTRAL_2 = 7,
	LUMI_SENSOR_CUBE = 8,
	LUMI_CTRL_NEUTRAL_1 = 9,
	LUMI_SENSOR_HT = 10,
	LUMI_PLUG = 11,
	
	LUMI_SENSOR_86SWITCH2 = 12,
	//LUMI_CTRL_CURTAIN = 13,
	LUMI_CURTAIN = 13,
	LUMI_SENSOR_86SWITCH1 = 14,
	//LUMI_CURTAIN = 15,
	LUMI_86PLUG = 17,
	
	LUMI_SENSOR_NATGAS = 18,
	LUMI_SENSOR_WEATHER = 19,
	LUMI_AQ_CTRL_LN1 = 20,
	LUMI_AQ_CTRL_LN2 = 21,
	//GE_DIMMABLE_LIGHTING = 32,
	//=====model >= 25 model no need join version
	
	LUMI_PLUG_ES = 25,
	LUMI_WEATHER_ES = 26,
	LUMI_SWITCH_ES = 27,
	LUMI_MOTION_ES = 28,
	LUMI_MAGNET_ES = 29,
	LUMI_LN2_ES = 30,
	LUMI_CUBE_ES = 31,
	GE_DIMMABLE_LIGHTING = 32,
	LUMI_HT_ES = 33,

	LUMI_PLUG_AQ = 50,
	LUMI_SWITCH_AQ = 51,
	LUMI_MOTION_AQ = 52,
	LUMI_MAGNET_AQ = 53,
	//======================================================================
	LUMI_SENSOR_IR = 41,
	LUMI_LIGHT_RGBW = 42,
	LUMI_UNKNOW = 0xFFFFFFF,
}device_model_e;
#endif

typedef enum {
    LUMI_GATEWAY = 0,
    LUMI_SENSOR_SWITCH = 1,
    LUMI_SENSOR_MOTION = 2,
    LUMI_SENSOR_MAGNET = 3,
    LUMI_ZIGBEE_COMMON_CONTROLLER = 4,
    LUTUO_ENOCEAN_CONTROLLER = 5,
    YEE_LIGHT_RGB = 6,
    LUMI_CTRL_NEUTRAL_2 = 7,
    LUMI_SENSOR_CUBE = 8,
    LUMI_CTRL_NEUTRAL_1 = 9,
    LUMI_SENSOR_HT = 10,
    LUMI_PLUG = 11,
    LUMI_SENSOR_86SWITCH2 = 12,
    LUMI_CTRL_CURTAIN = 13,
    LUMI_SENSOR_86SWITCH1 = 14,


	LUMI_SENSOR_SMOKE = 15,
	LUMI_SENSOR_DLOCK = 16,
	LUMI_86PLUG = 17,
	LUMI_SENSOR_NATGAS = 18,
	LUMI_SENSOR_WEATHER = 19,
	LUMI_AQ_CTRL_LN1 = 20,
	LUMI_AQ_CTRL_LN2 = 21,
	//model >= 25 model no need join version
	LUMI_PLUG_ES = 25,
	LUMI_WEATHER_ES = 26,
	LUMI_SWITCH_ES = 27,
	LUMI_MOTION_ES = 28,
	LUMI_MAGNET_ES = 29,
	LUMI_LN2_ES = 30,
	LUMI_CUBE_ES = 31,
	GE_DIMMABLE_LIGHTING = 32,
	LUMI_HT_ES = 33,
	LUMI_WLEAK_ES = 34,
	LUMI_CTRL_DUALCHN_ES = 35,
	LUMI_86SWITCH_ES = 36,
	LUMI_LN1_ES = 37,
	LUMI_HVAC_ES = 38,
	LUMI_CTRL_DIM3_ES = 39,
	LUMI_HTK_LOCK_ES = 40,
	LUMI_86PLUG_ES = 41,
	LUMI_CTRL_RGB_ES1 = 42,
	LUMI_CTRL_NEUTRAL1_ES1 = 43,
	LUMI_CTRL_NEUTRAL2_ES1 = 44,
	LUMI_CURTAIN_ES1 = 45,
	LUMI_86SWITCH1_ES1 = 46,
	LUMI_86SWITCH2_ES1 = 47,
//#endif

	LUMI_PLUG_AQ = 50,
	LUMI_SWITCH_AQ = 51,
	LUMI_MOTION_AQ = 52,
	LUMI_MAGNET_AQ = 53,
	LUMI_CTRL_DUALCHN_AQ = 54,
	LUMI_WLEAK_AQ = 55,
	LUMI_VIBRATION_AQ = 56,
	LUMI_HVAC_AQ = 57,
	LUMI_CTRL_DIM3_AQ1 = 58,
	LUMI_LOCK_AQ1 = 59,//HUI_TAI_LONG Lock
	LUMI_SWITCH_CUBE_AQ2 = 60,
	LUMI_CTRL_RGB_AQ1 = 61,
	//=======================
	LUMI_SENSOR_SWITCH_AK17 = 100,
	LUMI_SENSOR_MOTION_AS13 = 101,
	LUMI_SENSOR_MAGNET_AS11 = 102,
	LUMI_SENSOR_WLEAK_AS14 = 103,
	LUMI_WEATHER_AS15 = 104,
	LUMI_VIBRATION_AS12 = 105,

	//=========================homekit
	LUMI_SENSOR_CUBE_AQHM01 = 120,
	LUMI_SENSOR_SWITCH_AQHM01 = 121,
	LUMI_SENSOR_86SW1_AQHM01 = 122,
	LUMI_SENSOR_86SW2_AQHM01 = 123,
	LUMI_CTRL_NEUTRAL1_AQHM01 = 124,
	LUMI_CTRL_NEUTRAL2_QHM01 = 125,
	LUMI_CTRL_LN1_AQHM02 = 126,
	LUMI_CTRL_LN2_AQHM02 = 127,
	LUMI_SENSOR_MAGNET_AQHM01 = 128,
	LUMI_SENSOR_MOTION_AQHM01 = 129,
	LUMI_WEATHER_AQHM01 = 130,
	LUMI_VIBRATION_AQHM01 = 131,
	LUMI_SENSOR_WLEAK_AQHM01 = 132,

	//===================
	LUMI_MAGNET_AQ2 = 58,
  LUMI_LIGHT_RGBW = 80,
	LUMI_LOCK_V1 = 81,//Zhu_Hai_Wei_Ma Lock	
    LUMI_UNKNOW = 0xFFFFFFF,
	
} device_model_e;


#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
} /* end of the 'extern "C"' block */
#endif
#endif
